name: Sync Bluefin Releases

on:
  schedule:
    - cron: "0 10 * * *" # 6am US Eastern Time (ET) = 10:00 UTC
  workflow_dispatch:
  repository_dispatch:
    types: [bluefin-release]

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GitHub CLI
        run: |
          # GitHub CLI is pre-installed on ubuntu-latest
          gh --version

      - name: Process releases
        id: process
        run: |
          echo "Processing releases..."
          
          # Function to process a single release
          process_release() {
            local repo="$1"
            local tag="$2"
            local url="$3"
            local date="$4"
            local name="$5"
            local body="$6"
            
            echo "Processing $repo:$tag"
            
            # Call existing script to process release
            if ./scripts/process_single_release.sh "$repo" "$tag" "$url" "$date" "$name" "$body" "false" ""; then
              echo "✅ Processed $repo:$tag"
              return 0
            else
              echo "⚠️ Skipped $repo:$tag (already exists or error)"
              return 1
            fi
          }

          # Track processed releases
          PROCESSED_COUNT=0

          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            # Handle single release from repository dispatch
            TAG="${{ github.event.client_payload.tag_name }}"
            URL="${{ github.event.client_payload.html_url }}"
            
            # Determine source repo from URL
            if [[ "$URL" == *"bluefin-lts"* ]] || [[ "$TAG" == lts-* ]]; then
              REPO="ublue-os/bluefin-lts"
            else
              REPO="ublue-os/bluefin"
            fi
            
            # Get release details
            RELEASE_DATA=$(gh api repos/$REPO/releases/tags/$TAG 2>/dev/null || echo "{}")
            
            if [[ "$RELEASE_DATA" != "{}" ]]; then
              DATE=$(echo "$RELEASE_DATA" | jq -r '.published_at')
              NAME=$(echo "$RELEASE_DATA" | jq -r '.name // .tag_name')
              BODY=$(echo "$RELEASE_DATA" | jq -r '.body // ""')
              
              if process_release "$REPO" "$TAG" "$URL" "$DATE" "$NAME" "$BODY"; then
                PROCESSED_COUNT=$((PROCESSED_COUNT + 1))
              fi
            fi
          else
            # Handle scheduled/manual runs - get latest releases
            echo "Fetching latest releases from repositories..."
            
            # Get latest stable release from ublue-os/bluefin
            STABLE_RELEASE=$(gh api repos/ublue-os/bluefin/releases --jq '[.[] | select(.tag_name | contains("stable")) | select(.prerelease == false)][0]' 2>/dev/null || echo "null")
            
            if [[ "$STABLE_RELEASE" != "null" ]]; then
              TAG=$(echo "$STABLE_RELEASE" | jq -r '.tag_name')
              URL=$(echo "$STABLE_RELEASE" | jq -r '.html_url')
              DATE=$(echo "$STABLE_RELEASE" | jq -r '.published_at')
              NAME=$(echo "$STABLE_RELEASE" | jq -r '.name // .tag_name')
              BODY=$(echo "$STABLE_RELEASE" | jq -r '.body // ""')
              
              if process_release "ublue-os/bluefin" "$TAG" "$URL" "$DATE" "$NAME" "$BODY"; then
                PROCESSED_COUNT=$((PROCESSED_COUNT + 1))
              fi
            fi
            
            # Get latest GTS release from ublue-os/bluefin
            GTS_RELEASE=$(gh api repos/ublue-os/bluefin/releases --jq '[.[] | select(.tag_name | contains("gts"))][0]' 2>/dev/null || echo "null")
            
            if [[ "$GTS_RELEASE" != "null" ]]; then
              TAG=$(echo "$GTS_RELEASE" | jq -r '.tag_name')
              URL=$(echo "$GTS_RELEASE" | jq -r '.html_url')
              DATE=$(echo "$GTS_RELEASE" | jq -r '.published_at')
              NAME=$(echo "$GTS_RELEASE" | jq -r '.name // .tag_name')
              BODY=$(echo "$GTS_RELEASE" | jq -r '.body // ""')
              
              if process_release "ublue-os/bluefin" "$TAG" "$URL" "$DATE" "$NAME" "$BODY"; then
                PROCESSED_COUNT=$((PROCESSED_COUNT + 1))
              fi
            fi
            
            # Get latest LTS release from ublue-os/bluefin-lts
            LTS_RELEASE=$(gh api repos/ublue-os/bluefin-lts/releases/latest 2>/dev/null || echo "null")
            
            if [[ "$LTS_RELEASE" != "null" ]]; then
              TAG=$(echo "$LTS_RELEASE" | jq -r '.tag_name')
              URL=$(echo "$LTS_RELEASE" | jq -r '.html_url')
              DATE=$(echo "$LTS_RELEASE" | jq -r '.published_at')
              NAME=$(echo "$LTS_RELEASE" | jq -r '.name // .tag_name')
              BODY=$(echo "$LTS_RELEASE" | jq -r '.body // ""')
              
              if process_release "ublue-os/bluefin-lts" "$TAG" "$URL" "$DATE" "$NAME" "$BODY"; then
                PROCESSED_COUNT=$((PROCESSED_COUNT + 1))
              fi
            fi
          fi

          echo "processed_count=$PROCESSED_COUNT" >> $GITHUB_OUTPUT
          echo "Processed $PROCESSED_COUNT new releases"

      - name: Create Pull Request
        if: steps.process.outputs.processed_count != '0'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat(changelogs): sync ${{ steps.process.outputs.processed_count }} Bluefin release(s)"
          title: "feat(changelogs): sync ${{ steps.process.outputs.processed_count }} Bluefin release(s)"
          body: |
            ## Bluefin Release Sync
            
            This PR automatically syncs ${{ steps.process.outputs.processed_count }} new Bluefin release changelog(s).
            
            **Trigger:** ${{ github.event_name }}
            **Processed:** ${{ steps.process.outputs.processed_count }} release(s)
            
            Generated by the automated release sync workflow.
          branch: changelogs/sync-bluefin-releases
          delete-branch: true
          draft: false

      - name: Enable auto-merge
        if: steps.process.outputs.processed_count != '0'
        run: |
          # Get the PR number from the previous step
          PR_NUMBER=$(gh pr list --head changelogs/sync-bluefin-releases --json number --jq '.[0].number')
          
          if [[ -n "$PR_NUMBER" && "$PR_NUMBER" != "null" ]]; then
            echo "Enabling auto-merge for PR #$PR_NUMBER"
            gh pr merge $PR_NUMBER --auto --merge
            echo "✅ Auto-merge enabled for PR #$PR_NUMBER"
          else
            echo "⚠️ Could not find PR to enable auto-merge"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
